"""
Schemas module
Export all schemas
"""

from app.schemas.recording import (
    AISummaryResponse,
    BatchDeleteRequest,
    BatchMoveRequest,
    BatchTagRequest,
    FolderCreate,
    FolderResponse,
    RecordingCreate,
    RecordingDetail,
    RecordingListItem,
    RecordingUpdate,
    TagCreate,
    TagResponse,
    TranscriptResponse,
    TranscriptSegment,
    TranslationResponse,
)
from app.schemas.translation import (
    AddToVocabularyRequest,
    DictionaryDefinition,
    DictionaryResponse,
    TextTranslateRequest,
    TextTranslateResponse,
    TextTranslationHistory,
    TTSRequest,
    TTSResponse,
    VocabularyItem,
)
from app.schemas.user import (
    AdminCreateUser,
    AdminUpdateUser,
    ConfigTestRequest,
    ConfigTestResponse,
    DictConfig,
    LLMConfig,
    PasswordChange,
    PreferencesConfig,
    STTConfig,
    Token,
    TokenRefresh,
    TTSConfig,
    UserConfigResponse,
    UserConfigUpdate,
    UserLogin,
    UserRegister,
    UserResponse,
    UserUpdate,
)

__all__ = [
    # User
    "UserRegister",
    "UserLogin",
    "Token",
    "TokenRefresh",
    "UserResponse",
    "UserUpdate",
    "PasswordChange",
    "AdminCreateUser",
    "AdminUpdateUser",
    # Config
    "LLMConfig",
    "STTConfig",
    "TTSConfig",
    "DictConfig",
    "PreferencesConfig",
    "UserConfigResponse",
    "UserConfigUpdate",
    "ConfigTestRequest",
    "ConfigTestResponse",
    # Recording
    "TranscriptSegment",
    "FolderCreate",
    "FolderResponse",
    "TagCreate",
    "TagResponse",
    "RecordingCreate",
    "RecordingUpdate",
    "RecordingListItem",
    "RecordingDetail",
    "TranscriptResponse",
    "TranslationResponse",
    "AISummaryResponse",
    "BatchDeleteRequest",
    "BatchMoveRequest",
    "BatchTagRequest",
    # Translation
    "TextTranslateRequest",
    "TextTranslateResponse",
    "TextTranslationHistory",
    "DictionaryDefinition",
    "DictionaryResponse",
    "VocabularyItem",
    "AddToVocabularyRequest",
    "TTSRequest",
    "TTSResponse",
]
