"""add llm_fireworks_api_key

Revision ID: 787cacb89a44
Revises: d6987ce366cc
Create Date: 2025-12-29 21:50:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "787cacb89a44"
down_revision: str | None = "g7h8i9j0k1l2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_configs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("llm_fireworks_api_key", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_configs", schema=None) as batch_op:
        batch_op.drop_column("llm_fireworks_api_key")
    # ### end Alembic commands ###
