"""add_prompt_template_table

Revision ID: a888766a274e
Revises: bd6cb28ee3dd
Create Date: 2025-12-25 21:21:59.971238

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a888766a274e"
down_revision: str | Sequence[str] | None = "bd6cb28ee3dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('prompt_templates',
    # sa.Column('id', sa.CHAR(36), nullable=False),
    # sa.Column('user_id', sa.CHAR(36), nullable=False),
    # sa.Column('name', sa.String(length=100), nullable=False),
    # sa.Column('template_type', sa.String(length=20), nullable=False),
    # sa.Column('content', sa.Text(), nullable=False),
    # sa.Column('is_active', sa.Boolean(), nullable=False),
    # sa.Column('created_at', sa.DateTime(), nullable=False),
    # sa.Column('updated_at', sa.DateTime(), nullable=False),
    # sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    # sa.PrimaryKeyConstraint('id')
    # )
    # op.create_index(op.f('ix_prompt_templates_user_id'), 'prompt_templates', ['user_id'], unique=False)
    # op.drop_index(op.f('ix_token_usages_user_id'), table_name='token_usages')
    # op.drop_table('token_usages')
    # op.drop_table('audio_blobs')
    # op.alter_column('ai_summaries', 'chapters',
    #            existing_type=sa.TEXT(),
    #            type_=sa.JSON(),
    #            nullable=False,
    #            existing_server_default=sa.text("'[]'"))
    # op.alter_column('recordings', 'audio_format',
    #            existing_type=sa.VARCHAR(length=10),
    #            nullable=False,
    #            existing_server_default=sa.text("'opus'"))
    # op.alter_column('user_configs', 'audio_buffer_duration',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            existing_server_default=sa.text('4'))
    # op.alter_column('user_configs', 'silence_threshold',
    #            existing_type=sa.INTEGER(),
    #            nullable=False,
    #            existing_server_default=sa.text('(30)'))
    # op.alter_column('user_configs', 'silence_mode',
    #            existing_type=sa.VARCHAR(length=20),
    #            nullable=False,
    #            existing_server_default=sa.text("'manual'"))
    # op.alter_column('user_configs', 'silence_prefer_source',
    #            existing_type=sa.VARCHAR(length=20),
    #            nullable=False,
    #            existing_server_default=sa.text("'auto'"))
    # op.alter_column('user_configs', 'silence_threshold_source',
    #            existing_type=sa.VARCHAR(length=20),
    #            nullable=False,
    #            existing_server_default=sa.text("'default'"))
    # op.alter_column('users', 'can_use_admin_key',
    #            existing_type=sa.BOOLEAN(),
    #            nullable=False,
    #            existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "can_use_admin_key",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "user_configs",
        "silence_threshold_source",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'default'"),
    )
    op.alter_column(
        "user_configs",
        "silence_prefer_source",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'auto'"),
    )
    op.alter_column(
        "user_configs",
        "silence_mode",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'manual'"),
    )
    op.alter_column(
        "user_configs",
        "silence_threshold",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("(30)"),
    )
    op.alter_column(
        "user_configs",
        "audio_buffer_duration",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("4"),
    )
    op.alter_column(
        "recordings",
        "audio_format",
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
        existing_server_default=sa.text("'opus'"),
    )
    op.alter_column(
        "ai_summaries",
        "chapters",
        existing_type=sa.JSON(),
        type_=sa.TEXT(),
        nullable=True,
        existing_server_default=sa.text("'[]'"),
    )
    op.create_table(
        "audio_blobs",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("data", sa.BLOB(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "token_usages",
        sa.Column("id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("user_id", sa.VARCHAR(length=36), nullable=False),
        sa.Column("provider", sa.VARCHAR(length=50), nullable=False),
        sa.Column("model", sa.VARCHAR(length=100), nullable=False),
        sa.Column("prompt_tokens", sa.INTEGER(), nullable=False),
        sa.Column("completion_tokens", sa.INTEGER(), nullable=False),
        sa.Column("total_tokens", sa.INTEGER(), nullable=False),
        sa.Column("estimated_cost", sa.FLOAT(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_token_usages_user_id"), "token_usages", ["user_id"], unique=False)
    op.drop_index(op.f("ix_prompt_templates_user_id"), table_name="prompt_templates")
    op.drop_table("prompt_templates")
    # ### end Alembic commands ###
