"""add segment thresholds to user config

Revision ID: d6987ce366cc
Revises: fbc3d469e053
Create Date: 2025-12-26 22:03:59.276089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.core.types


# revision identifiers, used by Alembic.
revision: str = 'd6987ce366cc'
down_revision: Union[str, Sequence[str], None] = 'fbc3d469e053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_blobs')
    op.alter_column('ai_summaries', 'chapters',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('prompt_templates', 'id',
               existing_type=sa.CHAR(length=36),
               type_=app.core.types.UUID(length=36),
               existing_nullable=False)
    op.alter_column('prompt_templates', 'user_id',
               existing_type=sa.CHAR(length=36),
               type_=app.core.types.UUID(length=36),
               existing_nullable=False)
    op.alter_column('recordings', 'audio_format',
               existing_type=sa.VARCHAR(length=10),
               nullable=False,
               existing_server_default=sa.text("'opus'"))
    op.add_column('user_configs', sa.Column('segment_soft_threshold', sa.Integer(), nullable=False, server_default='50'))
    op.add_column('user_configs', sa.Column('segment_hard_threshold', sa.Integer(), nullable=False, server_default='100'))
    op.alter_column('user_configs', 'audio_buffer_duration',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('4'))
    op.alter_column('user_configs', 'silence_threshold',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('(30)'))
    op.alter_column('user_configs', 'silence_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'manual'"))
    op.alter_column('user_configs', 'silence_prefer_source',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'auto'"))
    op.alter_column('user_configs', 'silence_threshold_source',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'default'"))
    op.alter_column('users', 'can_use_admin_key',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'can_use_admin_key',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('user_configs', 'silence_threshold_source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'default'"))
    op.alter_column('user_configs', 'silence_prefer_source',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'auto'"))
    op.alter_column('user_configs', 'silence_mode',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'manual'"))
    op.alter_column('user_configs', 'silence_threshold',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('(30)'))
    op.alter_column('user_configs', 'audio_buffer_duration',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('4'))
    op.drop_column('user_configs', 'segment_hard_threshold')
    op.drop_column('user_configs', 'segment_soft_threshold')
    op.alter_column('recordings', 'audio_format',
               existing_type=sa.VARCHAR(length=10),
               nullable=True,
               existing_server_default=sa.text("'opus'"))
    op.alter_column('prompt_templates', 'user_id',
               existing_type=app.core.types.UUID(length=36),
               type_=sa.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('prompt_templates', 'id',
               existing_type=app.core.types.UUID(length=36),
               type_=sa.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('ai_summaries', 'chapters',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.create_table('audio_blobs',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('data', sa.BLOB(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
