"""add_provider_specific_api_keys

Revision ID: e135360ad0f7
Revises: 01dbaf1b7a3d
Create Date: 2025-12-24 02:22:58.202431

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e135360ad0f7"
down_revision: str | Sequence[str] | None = "01dbaf1b7a3d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('audio_blobs') # Skipped for safety
    # Skipped unrelated strictness types
    with op.batch_alter_table("user_configs", schema=None) as batch_op:
        batch_op.add_column(sa.Column("llm_groq_api_key", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("llm_siliconflow_api_key", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("stt_groq_api_key", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("stt_deepgram_api_key", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("stt_openai_api_key", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("stt_siliconflow_api_key", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "can_use_admin_key",
        existing_type=sa.BOOLEAN(),
        nullable=True,
        existing_server_default=sa.text("0"),
    )
    op.alter_column(
        "user_configs",
        "silence_threshold_source",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'default'"),
    )
    op.alter_column(
        "user_configs",
        "silence_prefer_source",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'auto'"),
    )
    op.alter_column(
        "user_configs",
        "silence_mode",
        existing_type=sa.VARCHAR(length=20),
        nullable=True,
        existing_server_default=sa.text("'manual'"),
    )
    op.alter_column(
        "user_configs",
        "silence_threshold",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("(30)"),
    )
    op.alter_column(
        "user_configs",
        "audio_buffer_duration",
        existing_type=sa.INTEGER(),
        nullable=True,
        existing_server_default=sa.text("4"),
    )
    op.drop_column("user_configs", "stt_siliconflow_api_key")
    op.drop_column("user_configs", "stt_openai_api_key")
    op.drop_column("user_configs", "stt_deepgram_api_key")
    op.drop_column("user_configs", "stt_groq_api_key")
    op.drop_column("user_configs", "llm_siliconflow_api_key")
    op.drop_column("user_configs", "llm_groq_api_key")
    op.alter_column(
        "recordings",
        "audio_format",
        existing_type=sa.VARCHAR(length=10),
        nullable=True,
        existing_server_default=sa.text("'opus'"),
    )
    op.alter_column(
        "ai_summaries",
        "chapters",
        existing_type=sa.JSON(),
        type_=sa.TEXT(),
        nullable=True,
        existing_server_default=sa.text("'[]'"),
    )
    op.create_table(
        "audio_blobs",
        sa.Column("id", sa.VARCHAR(length=36), nullable=True),
        sa.Column("data", sa.BLOB(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###
